[package]
name = "data_dragon"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.39", features = ["full"] }
serde = { version = "1", features = ["derive"] }
